version: "3"
services:
  chrome_node:
    image: selenium/node-chrome:4.8.1-20230306
    container_name: chrome_node
    shm_size: 2gb
    depends_on:
      - selenium_hub
    environment:
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - crypto-portfolio-microservices_test-env-network
  record_chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20230306
    container_name: record_chrome_video
    volumes:
      - ./target:/videos
    depends_on:
      - chrome_node
    environment:
      - DISPLAY_CONTAINER_NAME=chrome_node
      - FILE_NAME=temp_video.mp4
    networks:
      - crypto-portfolio-microservices_test-env-network
  selenium_hub:
    image: selenium/hub:4.8.1-20230306
    container_name: selenium_hub
    ports:
      - "4444:4444"
    networks:
      - crypto-portfolio-microservices_test-env-network
networks:
  crypto-portfolio-microservices_test-env-network:
    external: true
