version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.8.1-20230306
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - crypto-portfolio-microservices_test-env-network
  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20230306
    volumes:
      - ./target:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
    networks:
      - crypto-portfolio-microservices_test-env-network
  selenium-hub:
    image: selenium/hub:4.8.1-20230306
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - crypto-portfolio-microservices_test-env-network
networks:
  crypto-portfolio-microservices_test-env-network:
    external: true