eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

api:
  etherscan:
    baseUrl: https://api-goerli.etherscan.io/api
  polygonscan:
    baseUrl: https://api-testnet.polygonscan.com/api
  snowtrace:
    baseUrl: https://api-testnet.snowtrace.io/api

explorer:
  wallet:
    etherscan: https://goerli.etherscan.io/address/
    polygonscan: https://mumbai.polygonscan.com/address/
    snowtrace: https://testnet.snowtrace.io/address/