eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

server:
  port: 8082

spring:
  application:
    name: wallet-service

feign:
  circuitbreaker:
    enabled: true

cors:
  allowedOrigin: http://localhost:4200

api:
  etherscan:
    baseUrl: "https://api.etherscan.io/api"
    apiKey: ${ETHERSCAN_API_KEY}
    fixedDelayMillis: 1200
    maxRetryAttempts: 10
    validateBodyFieldName: status
    validationValue: 1
    maxWalletsPerRequest: 20
    maxWalletsCheck: 120