eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: crypto-price-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/cryptocurrency/**
        - id: wallet-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/wallet/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"