version: "3"
services:
  chrome_node:
    image: selenium/node-chrome:4.10.0
    container_name: chrome_node
    shm_size: 2gb
    depends_on:
      - selenium_hub
    environment:
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=60
    networks:
      - crypto-portfolio-microservices_test-env-network
  firefox_node:
    image: selenium/node-firefox:4.10.0
    container_name: firefox_node
    shm_size: 2gb
    depends_on:
      - selenium_hub
    environment:
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=60
    networks:
      - crypto-portfolio-microservices_test-env-network
  edge_node:
    image: selenium/node-edge:4.10.0
    container_name: edge_node
    shm_size: 2gb
    depends_on:
      - selenium_hub
    environment:
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=60
    networks:
      - crypto-portfolio-microservices_test-env-network
  record_chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20230614
    container_name: record_chrome_video
    volumes:
      - ./target:/videos
    depends_on:
      - chrome_node
    environment:
      - DISPLAY_CONTAINER_NAME=chrome_node
      - FILE_NAME=temp_video_chrome.mp4
    networks:
      - crypto-portfolio-microservices_test-env-network
  record_firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20230614
    container_name: record_firefox_video
    volumes:
      - ./target:/videos
    depends_on:
      - firefox_node
    environment:
      - DISPLAY_CONTAINER_NAME=firefox_node
      - FILE_NAME=temp_video_firefox.mp4
    networks:
      - crypto-portfolio-microservices_test-env-network
  record_edge_video:
    image: selenium/video:ffmpeg-4.3.1-20230614
    container_name: record_edge_video
    volumes:
      - ./target:/videos
    depends_on:
      - edge_node
    environment:
      - DISPLAY_CONTAINER_NAME=edge_node
      - FILE_NAME=temp_video_edge.mp4
    networks:
      - crypto-portfolio-microservices_test-env-network
  selenium_hub:
    image: selenium/hub:4.10.0
    container_name: selenium_hub
    ports:
      - "4444:4444"
    networks:
      - crypto-portfolio-microservices_test-env-network
networks:
  crypto-portfolio-microservices_test-env-network:
    external: true