name: "build-and-run-unit-integration-test"

env:
  COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
  AVALANCHE_API_KEY: ${{ secrets.AVALANCHE_API_KEY }}

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build discovery-server
        run: mvn -B package --file pom.xml -Dgroups="SmokeTest"
        working-directory: ./discovery-server/

      - name: Build gateway-service
        run: mvn -B package --file pom.xml -Dgroups="SmokeTest"
        working-directory: ./gateway-service/

      - name: Build crypto-price-service
        run: mvn -B package --file pom.xml -Dgroups="SmokeTest"
        working-directory: ./crypto-price-service/

      - name: Build wallet-service
        run: mvn -B package --file pom.xml -Dgroups="SmokeTest"
        working-directory: ./wallet-service/

      - name: Unit Test crypto-price-service
        run: mvn -B test -Dgroups="UnitTest"
        working-directory: ./crypto-price-service/

      - name: Unit Test wallet-service
        run: mvn -B test -Dgroups="UnitTest"
        working-directory: ./wallet-service/

      - name: Integration Test crypto-price-service
        run: mvn -B test -Dgroups="IntegrationTest"
        working-directory: ./crypto-price-service/

      - name: Integration Test wallet-service
        run: mvn -B test -Dgroups="IntegrationTest"
        working-directory: ./wallet-service/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}