name: "qa-regression-test"

env:
  COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
  AVALANCHE_API_KEY: ${{ secrets.AVALANCHE_API_KEY }}
  BRANCH_NAME: ${{ github.ref_name }}
  CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

on:
  push:
    branches:
      - 'CPA-*'

jobs:
  qa-tests-regression:
    if: ${{ contains(github.event.head_commit.message, '#regressionTest') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci --force
        working-directory: ./client-side

      - name: Build project
        run: npm run build -- --configuration=docker
        working-directory: ./client-side

      - name: Build microservices
        run: mvn -B package --file pom.xml -DskipTests

      - name: Start backend and frontend
        run: |
          docker-compose up -d

      - name: Start selenium grid
        run: docker-compose -f selenium-compose.yaml up -d
        working-directory: ./quality-assurance/qa-ui

      - name: List containers
        run: docker ps
        working-directory: ./quality-assurance/qa-ui

      - name: Sleep for 15s
        uses: juliangruber/sleep-action@v1
        with:
          time: 15s

      - name: Regression test
        run: mvn test -Dgroups="TrendLineChartUI"
        working-directory: ./quality-assurance/qa-ui

      - name: API test
        run: mvn test
        working-directory: ./quality-assurance/qa-api

      - name: Stop test env
        if: always()
        run: docker-compose -f selenium-compose.yaml down
        working-directory: ./quality-assurance/qa-ui

      - name: Stop backend and fronted
        if: always()
        run: docker-compose down

      - name: Fetch allure report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: quality-assurance/qa-ui/target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10
          subfolder: regression

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history