name: "qa-regression-test-firefox"

env:
  ####### TEST VARS #######
  TAGS: HomePageUI,TokenBalanceUI
  BROWSER_TYPE: firefox
  HEADLESS_MODE: enable
  NETWORK_LISTENER: disable
  PARALLEL_TEST: false

  ####### ENV VARS #######
  COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
  AVALANCHE_API_KEY: ${{ secrets.AVALANCHE_API_KEY }}
  BRANCH_NAME: ${{ github.ref_name }}
  CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

on:
  push:
    branches:
      - 'CPA-*'

jobs:
  qa-tests-regression-firefox:
    if: ${{ contains(github.event.head_commit.message, '#regressionTestAll') || contains(github.event.head_commit.message, '#regressionTestFirefox') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm ci --force
        working-directory: ./client-side

      - name: Build project
        run: npm run build -- --configuration=docker
        working-directory: ./client-side

      - name: Build microservices
        run: mvn -B package --file pom.xml -DskipTests

      - name: Create tests results dir
        run: mkdir -p quality-assurance/qa-ui/target/allure-results/

      - name: Start backend and frontend
        run: |
          docker-compose up -d

      - name: Start selenium grid
        run: docker-compose -f selenium-compose-firefox.yaml up -d
        working-directory: ./quality-assurance/qa-ui

      - name: List containers
        run: docker ps
        working-directory: ./quality-assurance/qa-ui

      - name: Sleep for 30s
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s

      - name: UI regression tests
        run: mvn test -T 2 -Dgroups="$TAGS" -Dbrowser="$BROWSER_TYPE" -Dheadless="$HEADLESS_MODE" -Dnetwork="$NETWORK_LISTENER" "-Djunit.jupiter.execution.parallel.enabled=$PARALLEL_TEST"
        working-directory: ./quality-assurance/qa-ui

      - name: Upload allure-results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-firefox
          path: ./quality-assurance/qa-ui/target/allure-results
          retention-days: 1
          if-no-files-found: error

  publish-report-firefox:
    if: ${{ contains(github.event.head_commit.message, '#regressionTestAll') || contains(github.event.head_commit.message, '#regressionTestFirefox') && always() }}
    needs: qa-tests-regression-firefox
    runs-on: ubuntu-latest
    concurrency: 1
    steps:
      - name: Download allure-results
        uses: actions/download-artifact@v3
        with:
          name: allure-results-firefox
          path: allure-results-firefox

      - name: Fetch allure report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results-firefox
          allure_history: allure-history/firefox
          keep_reports: 10
          subfolder: regression/firefox

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history/firefox