name: "Quality Assurance"

env:
  COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

on:
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ./client-side
      - name: Build project
        run: npm run build
        working-directory: ./client-side
      - name: Build microservices
        run: mvn -B package --file pom.xml -DskipTests
      - name: Start microservice
        run: |
          docker-compose up -d
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 90s
      - name: Get logs
        if: always()
        run: docker compose logs
      - name: Stop microservice
        if: always()
        run: docker-compose down
