name: Java CI

env:
  COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
#      - name: Build
#        run: mvn -B package --file pom.xml -Dgroups="SmokeTest"
#      - name: Unit Test
#        run: mvn -B test -Dgroups="UnitTest"
#      - name: Integration Test
#        run: mvn -B test -Dgroups="IntegrationTest"
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ./client-side
      - name: Build project
        run: npm run build
        working-directory: ./client-side
      - name: Build microservices
        run: mvn -B package --file pom.xml -DskipTests
      - name: Start microservice
        run: | 
          docker-compose up --abort-on-container-exit --exit-code-from crypto-price-service
      - name: Check service health
        run: |
          docker inspect --format='{{.State.Health.Status}}' container-name | grep -q 'healthy'
        env:
          container-name: crypto-price-service
#      - name: Wait for microservice to start
#        run: |
#          set -eo pipefail
#          docker-compose logs -f crypto-price-service 2>&1 | grep -q "Started Application" && echo "Microservice is up!"
      - name: Stop microservice
        run: docker-compose down
